object: orig/373307D9/default.xex
symbols: config/373307D9/symbols.txt
splits: config/373307D9/splits.txt

# (optional) Path to the DOL's .map file.
# This path is relative to the root of the project, and is _not_ affected by `object_base`.
# This should only used for initial analysis, and generating the symbols and splits files.
# Once those files are generated, remove this to avoid conflicts.
# map: orig/373307D9/ham_xbox_r.map

# Change this to match the linker version.
# See config.example.yml for a list.
# mw_comment_version: 11

# modules:
# - object: files/module.rel
#   hash: 0123456789abcdef0123456789abcdef01234567
#   symbols: config/GAMEID/module/symbols.txt
#   splits: config/GAMEID/module/splits.txt

# (optional) When enabled, function boundary analysis will be skipped.
# Only valid _after_ initial analysis has been performed and
# the symbols and splits files have been generated. 
# quick_analysis: true

# (optional) Whether to write disassembly to the split output directory.
# While not used in the build process, the disassembly is useful
# for reading and usage with other tools, like decomp.me.
# write_asm: false

add_relocations:
- source: .rdata:0x82089114
  type: abs
  target: merged_BufLockIdxSDVD
# Curl_http_readwrite_headers
- source: .text:0x82573474
  type: ha
  target: ??_C@_0CI@DLONMNKD@HTTP?11?40?5connection?5set?5to?5keep?5@
- source: .text:0x825734B4
  type: ha
  target: ??_C@_0BD@DNFFOCFM@Transfer?9Encoding?3?$AA@
- source: .text:0x825734BC
  type: ha
  target: ??_C@_05LBOHBHFK@close?$AA@
- source: .text:0x825734E8
  type: ha
  target: ??_C@_0M@HJBFCNNB@Connection?3?$AA@
- source: .text:0x82573500
  type: ha
  target: ??_C@_07KCKHAHHI@chunked?$AA@
- source: .text:0x8257351C
  type: ha
  target: ??_C@_0CG@GBJOIAPM@HTTP?11?41?5proxy?5connection?5set?5cl@
- source: .text:0x8257355C
  type: l
  target: ??_C@_07KCKHAHHI@chunked?$AA@
- source: .text:0x82573564
  type: l
  target: ??_C@_0BD@DNFFOCFM@Transfer?9Encoding?3?$AA@
- source: .text:0x8257356C
  type: l
  target: ??_C@_0CI@DLONMNKD@HTTP?11?40?5connection?5set?5to?5keep?5@
- source: .text:0x825735C4
  type: l
  target: ??_C@_0M@HJBFCNNB@Connection?3?$AA@
- source: .text:0x825735E0
  type: l
  target: ??_C@_0CG@GBJOIAPM@HTTP?11?41?5proxy?5connection?5set?5cl@
- source: .text:0x82573610
  type: l
  target: ??_C@_05LBOHBHFK@close?$AA@
# Curl_proxyCONNECT
- source: .text:0x82589F38
  type: ha
  target: ??_C@_0BD@DNFFOCFM@Transfer?9Encoding?3?$AA@
- source: .text:0x82589F44
  type: ha
  target: ??_C@_0BL@FDNFJOM@CONNECT?5responded?5chunked?6?$AA@
- source: .text:0x82589F54
  type: ha
  target: ??_C@_07KCKHAHHI@chunked?$AA@
- source: .text:0x82589F70
  type: l
  target: ??_C@_0BD@DNFFOCFM@Transfer?9Encoding?3?$AA@
- source: .text:0x82589F80
  type: l
  target: ??_C@_07KCKHAHHI@chunked?$AA@
- source: .text:0x82589F84
  type: l
  target: ??_C@_0BL@FDNFJOM@CONNECT?5responded?5chunked?6?$AA@
# ?Reteleport@HamCamShot@@QAAXABVVector3@@_NVSymbol@@@Z
- source: .text:0x824A6B94
  type: ha
  target: ?TheGameData@@3PAVHamGameData@@A
- source: .text:0x824A6DD0
  type: l
  target: ?TheGameData@@3PAVHamGameData@@A

# These are Windows error codes, not relocations!
block_relocations:
- target: .data:0x83010001
- target: .data:0x83010003
- target: .data:0x8301000B
- target: .data:0x8301000D
